# Generated by Django 4.2.6 on 2024-04-18 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicename', models.CharField(choices=[('Maid', 'Maid'), ('Carpet', 'Carpet'), ('Tile', 'Tile')], max_length=50)),
                ('servicedescription', models.TextField(max_length=1000)),
                ('services_image', models.ImageField(upload_to='services')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffname', models.CharField(max_length=200)),
                ('profession', models.CharField(choices=[('Maid', 'Maid'), ('Carpet', 'Carpet'), ('Tile', 'Tile')], max_length=50)),
                ('staffage', models.IntegerField()),
                ('staffaddress', models.CharField(max_length=200)),
                ('staffsummary', models.TextField()),
                ('staffdocument', models.ImageField(upload_to='document')),
                ('registerdate', models.DateTimeField(auto_now_add=True)),
                ('staffstatus', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted')], default='Pending', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingdate', models.DateField()),
                ('service', models.CharField(choices=[('Maid', 'Maid'), ('Carpet', 'Carpet'), ('Tile', 'Tile')], max_length=50)),
                ('telephone', models.IntegerField(unique=True)),
                ('address', models.CharField(max_length=250)),
                ('formdate', models.DateTimeField(auto_now_add=True)),
                ('bookingstatus', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted')], default='Pending', max_length=50)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.staff')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
