# Generated by Django 4.2.6 on 2024-04-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bookingstatus',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Pending', 'Pending')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staffstatus',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Pending', 'Pending')], default='Pending', max_length=50),
        ),
    ]
